### ISSUE TITLE
SchemaError: Failed validating 'pattern' - some not fixed

### ISSUE THREAD

**Issue by kilpert** [KohlbacherLab/dnpm-dip-api-gateway#6]
The same issue like in [SchemaError: Failed validating 'pattern' #3](https://github.com/KohlbacherLab/dnpm-dip-api-gateway/issues/3):
Some square brackets still remain. Today, I found in the downloaded schema:

"#de.dnpm.dip.coding.Coding[de.dnpm.dip.rd.model.RDDiagnosis.Category]"
"de.dnpm.dip.coding.Coding[de.dnpm.dip.rd.model.RDDiagnosis.Category]"

It should be:

"#de.dnpm.dip.coding.Coding_de.dnpm.dip.rd.model.RDDiagnosis.Category"
"de.dnpm.dip.coding.Coding_de.dnpm.dip.rd.model.RDDiagnosis.Category"

**Comment by lucienclin** [comment]
Oops, sorry I had missed that when I went after the previous issue.

Now it should all be solved.

Thank you very much for checking and reporting it!

**Comment by lucienclin** [comment]
P.S.
Sorry, an error had slipped in the schema derivation.
Not it should all be fixed.

**Comment by kilpert** [comment]
Thank you!
