### ISSUE TITLE
Feature request/proposal: Format schema json for easy tracking of changes

### ISSUE THREAD

**Issue by kilpert** [KohlbacherLab/dnpm-dip-api-gateway#7]
It would be nice if you could preformat the downloadable schema to make it consistent for easy tracking of changes. This is what I do:

`wget -O - https://dnpm.bwhealthcloud.de/api/rd/etl/patient-record/schema | jq --sort-keys | python -m json.tool >dnpm_dip_se.schema.json`

By doing this, you get these benefits:
  - key sorted file (`jq --sort-keys`)
  - pretty printed json (`python -m json.tool` => indent of 4 characters with spaces only)
  - easy **tracking of changes** (with diff, git diff, meld, etc.)

**Comment by lucienclin** [comment]
Thank you for the proposal.

In principle, this would be possible:

The schemas (which are derived from the Data Transfer Objects using [scala-jsonschema](https://github.com/andyglow/scala-jsonschema), as mentioned on the [API docs](https://github.com/KohlbacherLab/dnpm-dip-api-gateway/tree/main/app/controllers#json-schema-of-patient-record-payloads)) are currently stored as instances of [JsObject](https://www.playframework.com/documentation/3.0.x/api/scala/play/api/libs/json/JsObject.html) in the [API component](https://github.com/KohlbacherLab/dnpm-dip-api-gateway/blob/feaf6efd8c9133689308b9befaeb46368913a12f/app/controllers/de/dnpm/dip/rest/api/UseCaseRouter.scala#L73C52-L73C60).
These could instead be stored as String containing the formatted JSON (using [Json.prettyPrint](https://www.playframework.com/documentation/3.0.x/api/scala/play/api/libs/json/Json$.html)).
The only side-issue would then be that the response "content-type" on such schema requests wouldn't be "application/json" any more, but some "text" media type. 
If that's not a problem, I could adapt it

**Comment by lucienclin** [comment]
FYI:
I added some **experimental** "content negotiation" to the API endpoint for JSON schemas and exposed this on our demo system under `https://dnpm.bwhealthcloud.de/new_api/...`.  (note the `new_api` in the URI), e.g. `https://dnpm.bwhealthcloud.de/new_api/rd/etl/patient-record/schema`

This allows to specify the desired content type of the response via the `Accept` header:
- `Accept: */json` returns the serialized JSON schema object, i.e. _unformatted_ `application/json`
- `Accept: text/*` returns the JSON schema as _formatted_ `text/plain`

Note: Ideally the default returned content type without explicitly specified `Accept` range in the request would be `application/json`, but somehow this doesn't work yet, and such requests return the `text/plain`

Please let me know, if this goes in the right direction for you, then I can adjust the details.

**Comment by lucienclin** [comment]
I now made another adaptation:

Instead of the above usage, the schema-endpoint now always returns the _formatted_ JSON as content type `application/json`.

Please confirm if this matches your expectation, then I'll commit this.

**Comment by kilpert** [comment]
It does work! Thank you!
